# -*- coding: utf-8 -*-
"""vitor_nogueira_deep-learning_mlp_project2.ipynb.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vS2MTJE4OcwRcgSvrBQp-5Airq-JFaar
"""

"""
Flower Image Classification using ResNet18 Transfer Learning
Dataset: Kaggle Flowers Recognition (5 classes)
"""

import os
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torch.utils.tensorboard import SummaryWriter
from torchvision import transforms, models
from torchvision.models import ResNet18_Weights

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from tensorboard.backend.event_processing.event_accumulator import EventAccumulator
import kagglehub


# ==============================================================================
# 1. CONFIGURAÇÃO GLOBAL E REPRODUTIBILIDADE
# ==============================================================================

def set_seed(seed: int = 42) -> None:
    """Define sementes aleatórias para reprodutibilidade dos experimentos."""
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Dispositivo de execução selecionado: {device}")


# ==============================================================================
# 2. CARREGAMENTO E Mapeamento DO DATASET
# ==============================================================================

def load_dataset():
    """Baixa e mapeia os caminhos das imagens e rótulos do Kaggle Flowers."""
    path = kagglehub.dataset_download("alxmamaev/flowers-recognition")

    classes = sorted(['daisy', 'dandelion', 'rose', 'sunflower', 'tulip'])
    class_to_idx = {cls_name: i for i, cls_name in enumerate(classes)}

    base_dir = path
    for root, dirs, _ in os.walk(path):
        if set(classes).issubset(set(dirs)):
            base_dir = root
            break

    image_paths = []
    labels = []

    for cls_name in classes:
        cls_dir = os.path.join(base_dir, cls_name)
        if os.path.exists(cls_dir):
            for fname in os.listdir(cls_dir):
                if fname.lower().endswith(('.jpg', '.jpeg', '.png')):
                    image_paths.append(os.path.join(cls_dir, fname))
                    labels.append(class_to_idx[cls_name])

    return image_paths, labels, classes, class_to_idx

image_paths, labels, classes, class_to_idx = load_dataset()
print(f"Dataset carregado: {len(image_paths)} imagens distribuídas em {len(classes)} classes.")


# ==============================================================================
# 3. ANÁLISE EXPLORATÓRIA DE DADOS (EDA)
# ==============================================================================

def plot_eda(image_paths, labels, classes, class_to_idx):
    """Gera e salva gráficos exploratórios da distribuição de classes e amostras."""
    sns.set_theme(style="whitegrid")

    # Gráfico de distribuição
    fig, ax = plt.subplots(figsize=(8, 5), facecolor='white')
    df_counts = pd.DataFrame({'Classe': [classes[l] for l in labels]})
    sns.countplot(data=df_counts, x='Classe', palette='Set2', ax=ax, order=classes)

    ax.set_title('Distribuição das Imagens por Classe', fontweight='bold', fontsize=12)
    ax.set_xlabel('Classe')
    ax.set_ylabel('Quantidade de Imagens')
    ax.set_facecolor('white')

    for p in ax.patches:
        height = p.get_height()
        ax.annotate(f'{int(height)}', (p.get_x() + p.get_width() / 2., height + 15),
                    ha='center', va='bottom', fontsize=10)

    plt.tight_layout()
    fig.savefig('eda_flowers_distribution.png', dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()

    # Visualização de amostras
    fig_sample, axes_sample = plt.subplots(1, 5, figsize=(15, 3.5), facecolor='white')
    for i, cls_name in enumerate(classes):
        idx_cls = labels.index(class_to_idx[cls_name])
        img_sample = Image.open(image_paths[idx_cls])
        axes_sample[i].imshow(img_sample)
        axes_sample[i].set_title(cls_name.capitalize(), fontweight='bold')
        axes_sample[i].axis('off')

    plt.tight_layout()
    fig_sample.savefig('eda_flowers_samples.png', dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()

plot_eda(image_paths, labels, classes, class_to_idx)


# ==============================================================================
# 4. PREPARAÇÃO DOS DADOS E PIPELINE DE TRANSFORMAÇÃO
# ==============================================================================

class PyTorchFlowersDataset(Dataset):
    """Dataset customizado para carregamento e transformação de imagens de flores."""
    def __init__(self, image_paths, labels, transform=None):
        self.image_paths = image_paths
        self.labels = labels
        self.transform = transform

    def __len__(self):
        return len(self.image_paths)

    def __getitem__(self, idx):
        img_path = self.image_paths[idx]
        image = Image.open(img_path).convert('RGB')
        label = self.labels[idx]

        if self.transform:
            image = self.transform(image)

        return image, label


# Divisão estratificada dos dados (80% treino, 10% validação, 10% teste)
X_train_paths, X_temp_paths, y_train, y_temp = train_test_split(
    image_paths, labels, test_size=0.20, random_state=42, stratify=labels
)
X_val_paths, X_test_paths, y_val, y_test = train_test_split(
    X_temp_paths, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

# Definição das transformações e aumento de dados
mean_norm = [0.485, 0.456, 0.406]
std_norm = [0.229, 0.224, 0.225]

train_transform = transforms.Compose([
    transforms.RandomResizedCrop(224, scale=(0.8, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=20),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05),
    transforms.ToTensor(),
    transforms.Normalize(mean=mean_norm, std=std_norm)
])

val_test_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=mean_norm, std=std_norm)
])

# Inicialização dos DataLoaders
train_dataset = PyTorchFlowersDataset(X_train_paths, y_train, transform=train_transform)
val_dataset = PyTorchFlowersDataset(X_val_paths, y_val, transform=val_test_transform)
test_dataset = PyTorchFlowersDataset(X_test_paths, y_test, transform=val_test_transform)

batch_size = 32
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=2)


# ==============================================================================
# 5. ARQUITETURA E TREINAMENTO DO MODELO (TRANSFER LEARNING)
# ==============================================================================

def build_resnet18(num_classes: int = 5):
    """Carrega ResNet18 pré-treinada e substitui a camada de classificação."""
    model = models.resnet18(weights=ResNet18_Weights.DEFAULT)
    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(p=0.3),
        nn.Linear(in_features, num_classes)
    )
    return model

model = build_resnet18(num_classes=len(classes)).to(device)

criterion = nn.CrossEntropyLoss()
optimizer = optim.AdamW(model.parameters(), lr=1e-4, weight_decay=1e-4)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=2)

writer = SummaryWriter(log_dir='runs/flower_resnet18_experiment')
epochs = 15
best_val_loss = float('inf')
checkpoint_path = 'best_flower_resnet18.pt'

print("Iniciando o treinamento do modelo ResNet18...")

for epoch in range(1, epochs + 1):
    # Loop de Treino
    model.train()
    train_loss, train_correct, total_train = 0.0, 0, 0
    for X_b, y_b in train_loader:
        X_b, y_b = X_b.to(device), y_b.to(device)
        optimizer.zero_grad()
        outputs = model(X_b)
        loss = criterion(outputs, y_b)
        loss.backward()
        optimizer.step()

        train_loss += loss.item() * X_b.size(0)
        _, preds = torch.max(outputs, 1)
        train_correct += (preds == y_b).sum().item()
        total_train += y_b.size(0)

    ep_train_loss = train_loss / total_train
    ep_train_acc = train_correct / total_train

    # Loop de Validação
    model.eval()
    val_loss, val_correct, total_val = 0.0, 0, 0
    with torch.no_grad():
        for X_b, y_b in val_loader:
            X_b, y_b = X_b.to(device), y_b.to(device)
            outputs = model(X_b)
            loss = criterion(outputs, y_b)

            val_loss += loss.item() * X_b.size(0)
            _, preds = torch.max(outputs, 1)
            val_correct += (preds == y_b).sum().item()
            total_val += y_b.size(0)

    ep_val_loss = val_loss / total_val
    ep_val_acc = val_correct / total_val

    scheduler.step(ep_val_loss)

    writer.add_scalar('Loss/Train', ep_train_loss, epoch)
    writer.add_scalar('Loss/Val', ep_val_loss, epoch)
    writer.add_scalar('Accuracy/Train', ep_train_acc, epoch)
    writer.add_scalar('Accuracy/Val', ep_val_acc, epoch)

    if ep_val_loss < best_val_loss:
        best_val_loss = ep_val_loss
        torch.save(model.state_dict(), checkpoint_path)

    print(f"Época [{epoch:02d}/{epochs:02d}] | "
          f"Train Loss: {ep_train_loss:.4f} - Train Acc: {ep_train_acc * 100:.2f}% | "
          f"Val Loss: {ep_val_loss:.4f} - Val Acc: {ep_val_acc * 100:.2f}%")

writer.close()
print(f"Treinamento concluído. Checkpoint do melhor modelo salvo em: {checkpoint_path}")


# ==============================================================================
# 6. EXTRAÇÃO E VISUALIZAÇÃO DE MÉTRICAS (TENSORBOARD)
# ==============================================================================

def plot_tensorboard_metrics(log_dir: str):
    """Extrai os logs do TensorBoard e gera curvas de aprendizado."""
    event_files = [os.path.join(log_dir, f) for f in os.listdir(log_dir) if 'events.out' in f]
    if not event_files:
        print("Nenhum arquivo de log do TensorBoard encontrado.")
        return

    ea = EventAccumulator(event_files[0])
    ea.Reload()

    train_loss_tb = [s.value for s in ea.Scalars('Loss/Train')]
    val_loss_tb = [s.value for s in ea.Scalars('Loss/Val')]
    train_acc_tb = [s.value for s in ea.Scalars('Accuracy/Train')]
    val_acc_tb = [s.value for s in ea.Scalars('Accuracy/Val')]
    steps_tb = [s.step for s in ea.Scalars('Loss/Train')]

    fig, axes = plt.subplots(1, 2, figsize=(13, 4.5), facecolor='white')

    # Curva de Perda
    axes[0].set_facecolor('white')
    axes[0].plot(steps_tb, train_loss_tb, label='Train Loss', color='#0A345D', linewidth=2)
    axes[0].plot(steps_tb, val_loss_tb, label='Val Loss', color='#FF7043', linewidth=2)
    axes[0].set_title('CrossEntropy Loss', fontweight='bold')
    axes[0].set_xlabel('Época')
    axes[0].set_ylabel('Loss')
    axes[0].legend()
    axes[0].grid(True, linestyle='--', alpha=0.5)

    # Curva de Acurácia
    axes[1].set_facecolor('white')
    axes[1].plot(steps_tb, [a * 100 for a in train_acc_tb], label='Train Acc (%)', color='#1BB5D8', linewidth=2)
    axes[1].plot(steps_tb, [a * 100 for a in val_acc_tb], label='Val Acc (%)', color='#7CB342', linewidth=2)
    axes[1].set_title('Acurácia (%)', fontweight='bold')
    axes[1].set_xlabel('Época')
    axes[1].set_ylabel('Acurácia (%)')
    axes[1].legend()
    axes[1].grid(True, linestyle='--', alpha=0.5)

    plt.tight_layout()
    fig.savefig('cnn_learning_curves.png', dpi=300, bbox_inches='tight', facecolor='white')
    plt.close()

plot_tensorboard_metrics('runs/flower_resnet18_experiment')


# ==============================================================================
# 7. AVALIAÇÃO FINAL NO CONJUNTO DE TESTE
# ==============================================================================

model.load_state_dict(torch.load(checkpoint_path))
model.eval()

y_test_preds = []
with torch.no_grad():
    for X_b, _ in test_loader:
        X_b = X_b.to(device)
        out = model(X_b)
        _, preds = torch.max(out, 1)
        y_test_preds.extend(preds.cpu().numpy())

test_acc = accuracy_score(y_test, y_test_preds)

print("\n" + "=" * 60)
print(f"Acurácia no Conjunto de Teste (ResNet18): {test_acc * 100:.2f}%")
print("=" * 60)

print("\nRelatório de Classificação Detalhado:")
print(classification_report(y_test, y_test_preds, target_names=classes))

# Matriz de Confusão
fig, ax = plt.subplots(figsize=(7, 5.5), facecolor='white')
cm = confusion_matrix(y_test, y_test_preds)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax, xticklabels=classes, yticklabels=classes)
ax.set_title('Matriz de Confusão (Conjunto de Teste - ResNet18)', fontweight='bold')
ax.set_xlabel('Classe Prevista')
ax.set_ylabel('Classe Real')
ax.set_facecolor('white')

plt.tight_layout()
fig.savefig('resnet18_matriz_confusao.png', dpi=300, bbox_inches='tight', facecolor='white')
plt.close()